#!/usr/bin/env python3
"""
Generates a localized emoji data file (app/src/main/assets/ime/media/emoji/<locale>.txt) from CLDR annotations.

The emoji order, categories and skin tone variants are taken from root.txt, so a generated file always matches the
emoji palette. Names and keywords come from CLDR's common/annotations and common/annotationsDerived files.

Usage:
    python utils/generate_emoji_locale.py nl
    python utils/generate_emoji_locale.py nl --cldr-dir path/to/cldr/common
"""

import argparse
import pathlib
import unicodedata
import urllib.request
import xml.etree.ElementTree as ET

CLDR_VERSION = "48"
CLDR_RAW_URL = "https://raw.githubusercontent.com/unicode-org/cldr/release-{version}/common/{kind}/{locale}.xml"
EMOJI_ASSETS_DIR = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/assets/ime/media/emoji"
VARIATION_SELECTOR_16 = "\ufe0f"


def collation_key(keyword):
    """Approximates the ICU root collation the existing files were sorted with, so regenerated files keep their order:
    accents and case only break ties (lowercase first), and punctuation sorts before digits and letters."""
    folded = keyword.casefold().replace("œ", "oe").replace("æ", "ae")
    base = "".join(c for c in unicodedata.normalize("NFD", folded) if not unicodedata.combining(c))
    primary = [(1 if c.isalnum() else 0, c) for c in base]
    return primary, keyword.swapcase()


def read_annotation_xml(kind, locale, cldr_dir):
    if cldr_dir is not None:
        return (pathlib.Path(cldr_dir) / kind / f"{locale}.xml").read_bytes()
    url = CLDR_RAW_URL.format(version=CLDR_VERSION, kind=kind, locale=locale)
    # urlopen raises HTTPError for any non-2xx response
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read()


def load_annotations(locale, cldr_dir):
    """Returns a map of emoji (without VS16) to (name, keywords)."""
    names = {}
    keywords = {}
    for kind in ("annotations", "annotationsDerived"):
        root = ET.fromstring(read_annotation_xml(kind, locale, cldr_dir))
        for annotation in root.iter("annotation"):
            cp = annotation.get("cp")
            text = (annotation.text or "").strip()
            if not cp or not text or text == "↑↑↑":
                continue
            if annotation.get("type") == "tts":
                names[cp] = text
            else:
                keywords[cp] = sorted({k.strip() for k in text.split("|") if k.strip()}, key=collation_key)
    return {cp: (names.get(cp, ""), keywords.get(cp, [])) for cp in names.keys() | keywords.keys()}


def generate(locale, cldr_dir, out_path=None):
    annotations = load_annotations(locale, cldr_dir)
    template = (EMOJI_ASSETS_DIR / "root.txt").read_text(encoding="utf-8").splitlines()
    out = [
        f"# Auto-generated by utils/generate_emoji_locale.py using CLDR v{CLDR_VERSION}",
        "# DO NOT EDIT MANUALLY!",
    ]
    missing = 0
    for line in template:
        if line.startswith("# "):  # header comment; the keycap emoji line "#️⃣" starts with "#" too
            continue
        if not line.strip() or line.startswith("["):
            out.append(line)
            continue
        indent = "\t" if line.startswith("\t") else ""
        emoji = line.strip().split(";")[0]
        name, words = annotations.get(emoji.replace(VARIATION_SELECTOR_16, ""), ("", []))
        if not name:
            missing += 1
        out.append(f"{indent}{emoji};{name};{'|'.join(words)}")
    target = pathlib.Path(out_path) if out_path else EMOJI_ASSETS_DIR / f"{locale}.txt"
    target.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {target} ({missing} emojis without a {locale} name)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("locale", help="CLDR locale, for example nl")
    parser.add_argument("--cldr-dir", help="local CLDR common/ directory instead of downloading")
    parser.add_argument("--out", help="output file instead of the emoji assets directory")
    args = parser.parse_args()
    generate(args.locale, args.cldr_dir, args.out)
